# coding:utf-8

CHECK_LOG = False
# 打印到控制台的log级别 1-debug  2-info 3-warn 4-error
PRINT_LOG_LEVEL = 1
# 比对过程中不同的字典
DICT_DIFF_PARAM = {}
# 请求url所在文件的类型
# 1-txt已逗号间隔client_ip和参数url
# 2-csv
# 3-nginx日志
URL_FILE_TYPE = 2

# 后端的接口配置
INTERFACE_CONFIG = {
    "v3": {
        "expect_domain": "test-net.rayjump.com",
        "fact_domain": "test-adnet.rayjump.com",
        "url_path": "/openapi/ad/v3?",
        "method": "get",
        "response_type": "json",
        "headers": {},
        "request_data_path": "data/v3/{data_type}/{file_name}.csv",
        "response_data_type": "json",
        "set_pass": {r"data.session_id", r"data.parent_session_id",
                     r"data.ads.*.number_rating",r".*request_id", r".*\.k"},
        # "set_check_url": set(),
        "expect_corsair_req_log_path": "data/adn_logs/corsair/request/",
        "fact_corsair_req_log_path": "data/adn_logs/adnet/corsairreq/",
        "expect_stat_req_log_path": "data/adn_logs/stat_v3/request/cur_month/cur_date/",
        "fact_stat_req_log_path": "data/adn_logs/adnet/request/",
        "set_check_url": {r"data.only_impression_url", r"data.ads.*.impression_url", r"data.ads.*.notice_url", "data.ads.*.click_url", r"data.ads.*.ad_tracking.*"}
    },
    "ads": {
        0: {
            "name": "corsair",
            "host": "pre-net.rayjump.com",
            "url": "http://{0}/openapi/ads?",
            "method": "get",
            "request_data_type": "csv",
            "request_data_path": "data/ads/request_{0}.csv",
            "response_data_type": "json",
            "response_data_path": "data/ads/response_{0}.json",
            "set_pass": set()
        },
        1: {
            "name": "net",
            "host": "pre-net24.rayjump.com",
            "url": "http://{0}/openapi/ads?",
            "method": "get",
            "request_data_type": "csv",
            "request_data_path": "data/ads/request_{0}.csv",
            "response_data_type": "json",
            "response_data_path": "data/ads/response_{0}.json",
            "set_pass": set()
        }
    },
    "v2": {
        1: {
            "name": "mobvista",
            "host": "pre-midway.rayjump.com",
            "url": "http://{0}/openapi/ad/v2?",
            "method": "get",
            "headers": {},
            "request_data_type": "csv",
            "request_data_path": "data/v3/mobvista/request_{0}.csv",
            "response_data_type": "json",
            "response_data_path": "data/v3/mobvista/response_{0}.json",
            "set_pass": {"data.session_id", "data.parent_session_id"}
        },
        0: {
            "name": "net",
            "host": "pre-net.rayjump.com",
            "url": "http://{0}/openapi/ad/v2?",
            "method": "get",
            "headers": {},
            "request_data_type": "csv",
            "request_data_path": "data/v3/mobvista/request_{0}.csv",
            "response_data_type": "json",
            "response_data_path": "data/v3/mobvista/response_{0}.json",
            "set_pass": {"data.session_id", "data.parent_session_id"}
        }
    }

}
backend_url = {
    "1": "http://{0}/openapi/ad/v3?{1}",
    "2": "http://api.w.inmobi.com/showad/v3.1"
}

backend_host = {
    "1": "test-net.rayjump.com"
}

# 接口日志路径等信息配置
DICT_LOG = {
    "stat_v3": {
        "log_name": "stat_v3",
        "root_path": '/data/adn_logs/stat_v3/',
        "log_path": '/data/adn_logs/stat_v3/{log_type}/{cur_month}/{cur_date}/{cur_hour}.log',
        "log_key": "adn",
        "set_pass": set()
    },
    "midway": {
        "log_name": "midway",
        "root_path": '/data/adn_logs/midway/',
        "log_path": '/data/adn_logs/midway/{log_type}/{log_type}.log.{cur_hour}',
        "log_key": "midway",
        "set_pass": set()
    },
    "corsair": {
        "log_name": "corsair",
        "root_path": '/data/adn_logs/corsair/',
        "log_path": '/data/adn_logs/corsair/{log_type}/{log_type}.log.{cur_hour}',
        "log_key": "midway",
        "set_pass": {"created", "request_id"}
    },
    "adnet": {
       "log_name": "adnet",
        "root_path": '/data/adn_logs/adnet/',
        "log_path": '/data/adn_logs/adnet/{log_type}/{log_type}.log.{cur_hour}',
        "log_key": "adn",
        "set_pass": {"created", "request_id"}
    },
    "midway_tracking": {
        "log_name": "midway_tracking",
        'root_path': '/data/adn_logs/midway_tracking/',
        "log_path": '/data/adn_logs/midway_tracking/{log_type}/{cur_month}/{cur_date}/{cur_hour}.log',
        # "log_path": '/data/adn_logs/midway_tracking/{log_type}/{log_type}.log.{cur_hour}',
        "log_key": "midway",
        "set_pass": set()
    },
    "etl": {
        "log_name": "etl",
        'root_path': '/data/adn_logs/sync_data/receive_data',
        "log_path": '/data/adn_logs/sync_data/receive_data/receive_data_{log_type}/{cur_month}/{cur_date}/{cur_hour}.log',
        "log_key": "",
        "set_pass": set()
    },
    "record": {
        "log_name": "record",
        'root_path': '/data/adn_logs/record',
        "log_path": '/data/adn_logs/record/{log_type}/{cur_month}/{cur_date}/{cur_hour}.log',
        "log_key": "adn",
        "set_pass": set()
    }
}

# 搜索日志的相关信息配置
DICT_LOG_SEARCH = {
    "midway_req": {
        "expect": ["corsair", "request", 1, ""],
        "fact": ["adnet", "request", 1, ""],
        "pass": {"request_id"}
    },
    "adn_req": {
        "expect": ["stat_v3", "request", 1, ""],
        "fact": ["stat_v3", "request", 1, ""],
        "pass": {"request_id"}
    },
    "adn_pv": {
        "expect": ["stat_v3", "only_impression", 1, ""],
        "fact": ["stat_v3", "only_impression", 1, ""],
        "pass": {"request_id"}
    },
    "adn_imp": {
        "expect": ["stat_v3", "impression", 1, ""],
        "fact": ["stat_v3", "impression", 1, ""],
        "pass": {"request_id"}
    },
    "adn_click": {
        "expect": ["stat_v3", "click", 1, ""],
        "fact": ["stat_v3", "click", 1, ""],
        "pass": {"request_id"}
    },
    "adn_first": {
        "expect": ["stat_v3", "tracking", 1, '\"rate\":\"0\"+'],
        "fact": ["stat_v3", "tracking", 1, '\"rate\":\"0\"+'],
        "pass": {"request_id"}
    },
    "adn_second": {
        "expect": ["stat_v3", "tracking", 1, '\"rate\":\"25\"+'],
        "fact": ["stat_v3", "tracking", 1, '\"rate\":\"25\"+'],
        "pass": {"request_id"}
    },
    "adn_third": {
        "expect": ["stat_v3", "tracking", 1, '\"rate\":\"50\"+'],
        "fact": ["stat_v3", "tracking", 1, '\"rate\":\"50\"+'],
        "pass": {"request_id"}
    },
    "adn_fourth": {
        "expect": ["stat_v3", "tracking", 1, '\"rate\":\"75\"+'],
        "fact": ["stat_v3", "tracking", 1, '\"rate\":\"75\"+'],
        "pass": {"request_id"}
    },
    "adn_fifth": {
        "expect": ["stat_v3", "tracking", 1, '\"rate\":\"100\"+'],
        "fact": ["stat_v3", "tracking", 1, '\"rate\":\"100\"+'],
        "pass": {"request_id"}
    }
}

DICT_PARAM_KEYS = {
    'csp': [
        'MW_adBackend',
        'MW_adBackendData',
        'MW_flowTagId',
        'MW_randValue',
        'MW_backendConfig',
        'MW_adnum',
        'MW_tnum',
    ],
    'mp': [
        'requestId',
        'publisherId',
        'appId',
        'unitId',
        'MW_adBackend',
        'MW_adBackendData',
        'countryCode',
        'extra12',
        'platformId',
        'adTypeId',
        'osVersion',
        'sdkVersion',
        'appVersionName',
        'deviceBrand',
        'deviceModel',
        'screenSize',
        'orientation',
        'language',
        'networkTypeId',
        'MW_mcc_mnc',
        'ip',
        'remoteIp',
        'serverId',
        'imei',
        'mac',
        'devId',
        'googleAdvertisingId',
        'idfa',
        'MW_flowTagId',
        'MW_adnum',
        'MW_tnum',
        'MW_randValue',
        'MW_backendConfig',
        'MW_playInfo',
        'scenario'
    ],
    "p": [
        'publisherId',
        'appId',
        'unitId',
        'advertiserId',
        'campaignId',
        'creativeId',
        'scenario',
        'adType',
        'imageSize',
        'requestType',
        'platform',
        'osVersion',
        'sdkVersion',
        'deviceModel',
        'screenSize',
        'orientation',
        'countryCode',
        'language',
        'networkType',
        'mobileCode',
        'extra',
        'extra2',
        'extra3',
        'extra4',
        'extra5',
        'extra6',
        'extra7',
        'extra8',
        'extra9',
        'extra10',
        'requestId',
        'ip',
        'imei',
        'mac',
        'devId',
        'serverId',
        'reduce',
        'priceIn',
        'priceOut',
        'googleAdvertisingId',
        'idfa',
        'appVersionName',
        'deviceBrand',
        'remoteIp',
        'sessionId',
        'parentSessionId',
        'extra11',
        'extra12',
        'extra13',
        'extra14',
        'extra15',
        'extra16',
        'extra17',
        'extra18',
        'extra19',
        'extra20',
        'ext_btclass',
        'ext_finalsubid',
        'ext_deleteDevid',
        'ext_installFrom',
        'ext_stats',
        'ext_packageName',
        'ext_nativeVideo',
        'ext_flowTagId',
        'ext_cdnType',
        'ext_endcard',
        'ext_rushNoPre',
        'ext_dspRealAppid',
        'ext_finalPackageName',
        'ext_nativex',
        'ext_attr',
        'ext_stats2',
        'ext_adstacking',
        'ext_ctype',
        'ext_rv_template',
        'ext_abtest1',
        'ext_creativeCdnFlag',
        'ext_creativeSizeFlag',
        'ext_playable',
        'ext_priceIn',
        'ext_priceOut',
        'ext_b2t',
        'ext_channel',
        'ext_advInstallTime',
        'ext_threesInstallTime',
        'ext_abtest2',
        'ext_bp',
        'ext_source',
        'ext_reject',
        'ext_algo',
        'ext_thirdCid',
        'ext_ifLowerImp',
        'ext_nvt2',
        'ext_trueNvt2',
        'ext_systemUseragent'
    ],
    "q" :[
        'version',
        'domain',
        'requestId',
        'extra5',
        'publisherId',
        'appId',
        'unitId',
        'advertiserId',
        'campaignId',
        'priceIn',
        'priceOut',
        'extra',
        'requestType',
        'countryCode',
        'extra8',
        'extra10',
        'extra13',
        'extra14',
        'extra12',
        'appVersionName',
        'scenario',
        'extra16',
        'extra19',
        'end',
        'extra7',
        'ext_btclass',
        'ext_finalsubid',
        'ext_deleteDevid',
        'ext_installFrom',
        'ext_nativeVideo',
        'ext_flowTagId',
        'ext_cdnType',
        'ext_endcard',
        'ext_rushNoPre',
        'ext_dspRealAppid',
        'ext_finalPackageName',
        'ext_nativex',
        'creativeId',
        'ext_attr',
        'ext_adstacking',
        'ext_ctype',
        'ext_rv_template',
        'ext_abtest1',
        'ext_playable',
        'ext_b2t',
        'ext_channel',
        'ext_abtest2',
        'ext_bp',
        'ext_source'
    ],
    "r": ["r"]

}

DICT_PARAM_KEYS_PASS = {
    'csp': set(),
    'mp': {"requestId"},
    'p': {"requestId"},
    'q': {"requestId"}
}


DICT_LOG_KEYS = {
    "adn": [
        'date',
        'time',
        'created',
        'publisherId',
        'appId',
        'unitId',
        'advertiserId',
        'campaignId',
        'creativeId',
        'scenario',
        'adType',
        'imageSize',
        'requestType',
        'platform',
        'osVersion',
        'sdkVersion',
        'deviceModel',
        'screenSize',
        'orientation',
        'countryCode',
        'language',
        'networkType',
        'mobileCode',
        'extra',
        'extra2',
        'extra3',
        'extra4',
        'extra5',
        'extra6',
        'extra7',
        'extra8',
        'extra9',
        'extra10',
        'requestId',
        'ip',
        'imei',
        'mac',
        'devId',
        'serverId',
        'reduce',
        'priceIn',
        'priceOut',
        'googleAdvertisingId',
        'idfa',
        'appVersionName',
        'deviceBrand',
        'remoteIp',
        'sessionId',
        'parentSessionId',
        'extra11',
        'extra12',
        'extra13',
        'extra14',
        'extra15',
        'extra16',
        'extra17',
        'extra18',
        'extra19',
        'extra20',
        'ext_btclass',
        'ext_finalsubid',
        'ext_deleteDevid',
        'ext_installFrom',
        'ext_stats',
        'ext_packageName',
        'ext_nativeVideo',
        'ext_flowTagId',
        'ext_cdnType',
        'ext_endcard',
        'ext_rushNoPre',
        'ext_dspRealAppid',
        'ext_finalPackageName',
        'ext_nativex',
        'ext_attr',
        'ext_stats2',
        'ext_adstacking',
        'ext_ctype',
        'ext_rv_template',
        'ext_abtest1',
        'ext_creativeCdnFlag',
        'ext_creativeSizeFlag',
        'ext_playable',
        'ext_priceIn',
        'ext_priceOut',
        'ext_b2t',
        'ext_channel',
        'ext_advInstallTime',
        'ext_threesInstallTime',
        'ext_abtest2',
        'ext_bp',
        'ext_source',
        'ext_reject',
        'ext_algo',
        'ext_thirdCid',
        'ext_ifLowerImp',
        'ext_nvt2',
        'ext_trueNvt2',
        'ext_systemUseragent',
        'wxt_autoClick'
    ],
    "midway": [
        "date",
        "created",
        "request_id",
        "publisherId",
        "appId",
        "unitId",
        "ad_backend",
        "ad_backend_data",
        "countryCode",
        "city_code",
        "platform",
        "adType",
        "osVersion",
        "sdkVersion",
        "appVersionName",
        "deviceBrand",
        "deviceModel",
        "screensize",
        "orientation",
        "language",
        "networkType",
        "mcc_mnc",
        "client_ip",
        "remoteIp",
        "server_ip",
        "imei",
        "mac",
        "android_id",
        "gaid",
        "idfa",
        "flow_tag_id",
        "request_num",
        "true_num",
        "rand_value",
        "backend_config",
        "play_info",
        "scenario"
    ]
}
